server:
  port: 8080

spring:
  application:
    name: api-gateway

  data:

    redis:
      host: localhost
      port: 6379

  cloud:
    gateway:
      server:
        webflux:
          routes:

            # Product Service
            - id: product-service
              uri: lb://product-service
              predicates:
                - Path=/api/products/**
              filters:
                - name: RequestRateLimiter
                  args:
                    key-resolver: "#{@ipKeyResolver}"
                    redis-rate-limiter.replenishRate: 5
                    redis-rate-limiter.burstCapacity: 5

            # User Service
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/users/**

            # Cart Service
            - id: cart-service
              uri: lb://cart-service
              predicates:
                - Path=/api/cart/**

            # Order Service
            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/api/orders/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: your-very-long-secret-key-change-this