spring:
  application:
    name: order-service

  datasource:
    url: jdbc:mysql://db:3306/order_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

  show-sql: true

  properties:
    hibernate:
      format_sql: true

  kafka:
    bootstrap-servers: kafka-1:19092,kafka-2:19092,kafka-3:19092

server:
  port: 8083

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

resilience4j:

  retry:
    instances:
      productServiceRetry:
        max-attempts: 3
        wait-duration: 1s

  circuitbreaker:
    instances:
      productService:
        slidingWindowSize: 2
        minimumNumberOfCalls: 2
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3

  timelimiter:
    instances:
      productServiceTimeLimiter:
        timeout-duration: 2s
        cancel-running-future: true